#src/config.py

GRID_WIDTH = 10
GRID_HEIGHT = 10
GRID_SIZE = 30

SCREEN_WIDTH = GRID_WIDTH * GRID_SIZE
SCREEN_HEIGHT = GRID_HEIGHT * GRID_SIZE

BACKGROUND_COLOR = (0, 0, 0)
GRID_COLOR = (255, 255, 255)

